const ACT = {
    SIGNUP_USER:"SIGNUP_USER",
    SAVE_USER:"SAVE_USER",
    LOGIN_USER:"LOGIN_USER",
    GET_ALL_USER:"GET_ALL_USER",
    ALL_USER_LIST:"ALL_USER_LIST",
    DELETE_USER_ACTION:"DELETE_USER_ACTION",
}

export {ACT};